services:
  postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
  mysql:
    image: mysql:8.0.27
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./volume/mysql:/var/lib/mysql
    cap_add:
      - SYS_NICE
  redis:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./volume/redis/etc:/usr/local/etc/redis
      - ./volume/redis/data:/data
  mongo:
    image: mongo:5.0.5-focal
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./volume/mongo:/data/db
  couch:
    image: couchdb:3.2.0
    restart: unless-stopped
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: root
      COUCHDB_PASSWORD: password
      # I found these secret and flags on some Github repo, so I thought I'd use it and it worked.
      COUCHDB_SECRET: 0ef656e4-afa6-11ea-b3de-0242ac130004
      ERL_FLAGS: "-setcookie 556d8dd-e921-4e84-8f4c-011a69969724"
    volumes:
      - "./volume/couch/data:/opt/couchdb/data"
      - "./volume/couch/cfg:/opt/couchdb/etc/local.d"
  cassandra:
    image: cassandra:4.0.1
    restart: unless-stopped
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    volumes:
      - "./volume/cassandra/:/var/lib/cassandra"
  elasticsearch:
    image: elasticsearch:7.14.2
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - "./volume/elasticsearch/:/usr/share/elasticsearch/data"
  influxdb:
    image: influxdb:2.1.1-alpine
    restart: unless-stopped
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: root
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: root
      DOCKER_INFLUXDB_INIT_BUCKET: public
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: tQXMrSibyzgpothTPkYWArELdcXiPwQq
    volumes:
      - "./volume/influxdb/:/var/lib/influxdb"
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: unless-stopped
    ports:
      - 2083:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: redis
    ports:
      - 2084:8081
    depends_on:
      - redis
  adminer:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    ports:
      - 2086:8081
    depends_on:
      - mysql
      - postgres
